import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import {NextIntlClientProvider} from 'next-intl';
const locales = ['en', 'zh'];
import {notFound} from 'next/navigation';
import Header from './components/Header';
import Footer from './components/Footer';
const inter = Inter({ subsets: ['latin'] })
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: {locale}
}: {
    children: React.ReactNode;
    params: {locale:string}
  }) {
  const isValidLocale = locales.some((cur) => cur === locale)
  if (!isValidLocale) notFound()
  let messages;
  messages = (await import(`@/messages/${locale}.json`)).default;
  return (
    <html lang={locale}>
      <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Header />
        {children}
          <Footer />
          </NextIntlClientProvider>
      </body>
    </html>
  )
}
